name: cleaning_schedule
description: "Une app pour gÃ©rer un atelier de nettoyage."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  pdf: ^3.11.0
  printing: ^5.13.2
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  firebase_core_platform_interface: any

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png

# ðŸš€ Configuration du package flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
